### ISSUE TITLE
Is this really an extension?

### ISSUE THREAD

**Issue by chiefGui** [suevalov/async.backbone.validation#1]
By the title is easy to understand the subject of this issue: is this really an extension?

I looked to the code and it seems to be a replacement of the original Backbone.Validation. Am I right? Because if so, it could be a waste of functionality and code quality wether using this "version".

**Comment by suevalov** [comment]
@chiefGui It's a replacement and the version is outdated, unfortunately.

**Comment by chiefGui** [comment]
Oh yeah. I am creating my own way of asynchronous validation attached to Backbone.Validation as a module.

Soonish it should be released.

Thanks!
