### ISSUE TITLE
Deferred.reject ignoring error message

### ISSUE THREAD

**Issue by ghost** [suevalov/async.backbone.validation#2]
When deferred.reject(errorMessage) is called from validator, default message is still used.
(At least I think that's the API).

Error is on line 172:
                            // therefore consider the validation process to
                            // be resolved. Resolve the master deferred.
                            masterDeferred.resolve();

```
                    },
                    function (errorMessage) {

                        // Reject the master deferred.
                        masterDeferred.reject(validator.msg); // HERE
                        // masterDeferred.reject(errorMessage || validator.msg); (Possible correction) 

                    }
                );
```

**Comment by suevalov** [comment]
@jurajMatus, pull requests are welcome :)
I haven't updated this library for a while, not sure that it's still up to date.

**Comment by ghost** [comment]
Okay, thanks for response.
I have created a pull request, but I'm not very experienced with git, so maybe it's not done in a correct way.
